apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    name: nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx-app
    type: front-end
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30011
